//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisApp.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServisApp.Util.CustomErrorMessages", typeof(CustomErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ispravnu email adresu.
        /// </summary>
        public static string CustomEmail {
            get {
                return ResourceManager.GetString("CustomEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite broj između {1} i {2}.
        /// </summary>
        public static string CustomRangeMinMax {
            get {
                return ResourceManager.GetString("CustomRangeMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite {0}.
        /// </summary>
        public static string CustomRegularExpressionSelectList {
            get {
                return ResourceManager.GetString("CustomRegularExpressionSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikacioni broj sastoji se od 12 cifara.
        /// </summary>
        public static string CustomREIdBroj {
            get {
                return ResourceManager.GetString("CustomREIdBroj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj mobitela mora biti u formatu: +xxx xx xxx xxx(x).
        /// </summary>
        public static string CustomREMobileNumber {
            get {
                return ResourceManager.GetString("CustomREMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora biti dužine min 8 karaktera i mora sadržavati bar 3 od 4 karaktera: veliko slovo (A-Z), malo slovo (a-z), broj (0-9) i specijalni karakter (npr. !@#$%^&amp;*).
        /// </summary>
        public static string CustomREPassword {
            get {
                return ResourceManager.GetString("CustomREPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona mora biti u formatu: +xxx xx xxx xxx.
        /// </summary>
        public static string CustomREPhoneNumber {
            get {
                return ResourceManager.GetString("CustomREPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ponude mora biti u formatu: bbbb-mm-gg.
        /// </summary>
        public static string CustomREPonuda {
            get {
                return ResourceManager.GetString("CustomREPonuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite {0}.
        /// </summary>
        public static string CustomRequired {
            get {
                return ResourceManager.GetString("CustomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj izvještaja mora biti u formatu: bbbb-mm-gg.
        /// </summary>
        public static string CustomREReport {
            get {
                return ResourceManager.GetString("CustomREReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ugovora mora biti u formatu: bbbb-mm-gg.
        /// </summary>
        public static string CustomREUgovor {
            get {
                return ResourceManager.GetString("CustomREUgovor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj radnog naloga mora biti u formatu: bbb-mm/gg.
        /// </summary>
        public static string CustomREWorkOrder {
            get {
                return ResourceManager.GetString("CustomREWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalna dužina unosa je {1} karaktera.
        /// </summary>
        public static string CustomStringLengthMax {
            get {
                return ResourceManager.GetString("CustomStringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos mora biti između {2} i {1} karaktera.
        /// </summary>
        public static string CustomStringLengthMaxMin {
            get {
                return ResourceManager.GetString("CustomStringLengthMaxMin", resourceCulture);
            }
        }
    }
}
